# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0c8be364cb42ec753c819f31e6850f95f2db21821ae66cd51f54bd36fd835a49d922c6184b33a76a67ecdbee997d578cede135f8306d3ce9442fc6b6b95156f

test:
  secret_key_base: f950abad5fdb9d2bbcd03ff6051aace1918f4dc052b86a0ffbaf55a78f0e1cd9e9500e33d3906d4984cd8629ad4a5e2216e6c88169ea3b5bb8530b5281d787e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
